### ISSUE TITLE
Would be nice to be able to ignore lines from coverage

### ISSUE THREAD

**Issue by eseidelGoogle** [dart-lang/coverage#162]
I'm not sure how one best would implement this (or if it's even possible), but there are certain lines of code in dart which are intentionally unreachable, an example of such is a private constructor.

```
class Colors {
   Colors._();
}
```
Which is a pattern used to make a class non-constructable.  It's silly that coverage tells me that this line is uncovered:
https://coveralls.io/builds/9847810/source?filename=lib%2Fsrc%2Fmaterial%2Fcolors.dart

But I'm aware of no way with package:coverage to avoid that?

I could imagine a comment syntax, or maybe just teaching package:coverage about this specific idiom?  Not sure.

This is not a high priority, but would be nice to have for projects trying for high line or file coverage numbers.

**Comment by jtmcdole** [comment]
What about @Coverage(false) or @NotCovered

**Comment by eseidelGoogle** [comment]
I didn't know that was a thing.  Thanks!

**Comment by jtmcdole** [comment]
It is not a thing, I was just suggesting a thing!

**Comment by eseidelGoogle** [comment]
Oh, sorry.

**Comment by eseidelGoogle** [comment]
The only downside of that, it that it likely means you have to incldue package:coverage as a dependency in your package, which seems suboptimal.

**Comment by jtmcdole** [comment]
Solid point & agreed.  I was trying to use:

```dart
  void _();
```

And convert the class to abstract (its a static warehouse), but I'm getting warnings about it being unused in strong mode... which seems odd at first and then expected since it is private and nothing in the library is using it.

**Comment by zoechi** [comment]
or 

```dart
// ignore: coverage
```
like used to suppress linter warnings

**Comment by cbracken** [comment]
It'd be a relatively substantial change to support this at the source level. Right now coverage collection doesn't look at the source at all, though it's available via the VM service so long as you're not running from a snapshot. When running from a snapshot, the VM *will* provide source reconstituted from the tokenised source (and line numbers will match up) but comments are stripped. I suspect that in *most* cases, it's reasonable to require that developers run from source rather than a snapshot for coverage, but that'll exclude `dart:` libraries for example.

An alternative approach would be to post-process the source off disk.

**Comment by cbracken** [comment]
On the specific issue here, I wonder if we can identify a set of conditions under which code should be marked as non-coverable by default, like the case @eseidelGoogle mentions above: private constructors with no invocations within the library.

**Comment by dnfield** [comment]
Would it make sense to have this be driven upstream by the observatory report?  Perhaps having some kind of flag/attribute/comment the observatory could use to indicate that a file/class/method/set of lines are to be excluded.

**Comment by leisim** [comment]
Is there any news on this feature? It would be really convenient 👍

**Comment by lmckenzie** [comment]
Please add this.

**Comment by JZ-at-TP** [comment]
Almost a year. There is currently no way to get 100% coverage without this, or the ability to mock static class methods.

**Comment by cbracken** [comment]
Just to set expectations, this is not something that's likely to be worked on by us in the near future. I'd be more than happy to review community contributions that cleanly resolve this issue though.

A proper solution likely involves integrating with package:analyzer. A couple things that make this a bit trickier:
1. We probably want to avoid relying on defining any annotations in this package. Using something like `@coverage(false)` requires package:coverage to be a real dependency not just a `dev_dependency` in pub. A simple option here is to do what the linter does and rely on a comment immediately above the line/block of code in question. e.g. `// coverage: false`
1. Coverage collection doesn't currently rely on the source code (formatting in pretty print mode does, but doesn't compute or resolve an AST). We'd want any dependency on the source code to be strictly opt-in, since there are cases where the code being executed and the code on disk may differ -- e.g. when codegen is in use. As a particularly egregious case, imagine something akin to pub transformers, which are fortunately no longer supported. Script sources *can* be collected from the VM, but I can't remember if comments are retained.
1. Another reason to make this opt-in and disabled by default is the likely performance hit involved in reading in the source code, computing an AST, then applying a set of rules to that AST to selectively ignore coverage.

As noted above, I'm more than happy to review any community contributions that implement this.

**Comment by wouterhardeman** [comment]
Hey @cbracken,

I'm currently working on a PR. Thanks for the pointers. My current solution searches the source file for certain comments. It extracts the ignored line numbers and excludes them from the hitmap. Currently I have implemented:

* `// coverage:ignore-line`: ignores the current line of code
* `// coverage:ignore-start`: starts ignoring all next lines
* `// coverage:ignore-end`: stops ignoring lines

I still have to implement the opt-in argument.

I'll create a pull request tomorrow. I'm looking forward to your review!

**Comment by Justin-Randall** [comment]
Whatever happened with the PR?

**Comment by vysotsky** [comment]
Is there any chance to get this feature working? We're using code generation for Protobuf and seems we're getting wrong coverage 😞

**Comment by vysotsky** [comment]
Ok. If someone's interested, I've solved the problem by editing lcov.info itself.
```
flutter test --coverage
lcov --remove coverage/lcov.info "lib/generated/*" -o coverage/lcov_cleaned.info
genhtml -o coverage coverage/lcov_cleaned.info --no-function-coverage -s -p `pwd`
```
It helps to remove unneeded files

**Comment by rknell** [comment]
@vysotsky does that just remove references to files? Is there a way to filter individual lines?

**Comment by egarson** [comment]
@rknell: No, that's not supported by lcov.
While we're at it, there is also a pub package that will post-process an lcov file to remove files: [remove_from_coverage](https://pub.dev/packages/remove_from_coverage).

**Comment by fatherOfLegends** [comment]
According to the readme it appears like this was completed.

> Ignore lines from coverage
// coverage:ignore-line to ignore one line.
// coverage:ignore-start and // coverage:ignore-end to ignore range of lines inclusive.
// coverage:ignore-file to ignore the whole file.

Looking in the change log show this: 

> 0.14.0 - 2020-06-04
Add flag --check-ignore that is used to ignore lines from coverage depending on the comments.
Use // coverage:ignore-line to ignore one line. Use // coverage:ignore-start and // coverage:ignore-end to ignore range of lines inclusive. Use // coverage:ignore-file to ignore the whole file.

#302 

I think this issue can be closed.

That said I want to use this in a Flutter context.

I see this in the flutter codebase: https://github.com/flutter/flutter/pull/61408
Looks like it should be in the latest stable release of Flutter but it does not appear to work.

**Comment by cbracken** [comment]
Yep this can definitely be closed. This should be on the current beta branch for Flutter, and will roll out in the next stable release.

**Comment by fatherOfLegends** [comment]
@cbracken Thanks for your help! I see the commit linked below in the Flutter codebase and it is tagged with `1.22.0` the current stable release. I thought that would mean it is available. I am excited to see it coming in the next stable release but I must be misunderstanding how to determine what release a feature will be in. I am curious if you can tell me how to determine what flutter version this in included in? Thanks again!

https://github.com/flutter/flutter/commit/5c9d09f05ac70152062983535353b7bd1c101072#commitcomment-42931558
