### ISSUE TITLE
Test coverage marks asserts as unexecuted if the clause evaluates to true

### ISSUE THREAD

**Issue by xster** [dart-lang/coverage#251]
There's a lot of code in Flutter where we're verifying our assumptions and states via asserts in code like https://coveralls.io/builds/22463149/source?filename=lib/src/foundation/binding.dart#L211

Though they all seem to report DA:x,0 after running tests with coverage collection.

Evaluating to false like https://coveralls.io/builds/22463149/source?filename=lib/src/cupertino/date_picker.dart#L179 or evaluating a closure like https://coveralls.io/builds/22463149/source?filename=lib/src/widgets/heroes.dart#L222 seem to get counted though.

Any thoughts on what this might be and if it's intended behavior?

**Comment by cbracken** [comment]
Just to verify -- the code under test is executing with asserts enabled i.e. these are debug mode tests?

**Comment by xster** [comment]
Yes. As seen by execution of code inside of assert closures.

**Comment by xster** [comment]
Oh, you made this library. Ha

**Comment by leisim** [comment]
I have the same problem :/

**Comment by ZichangG** [comment]
VM uses function calls to determine. Callsites that have been executed will be considered as a hit.

If a variable is evaluated, like `assert(mode == null)`, an implicit getter function will be called if it is not a local variable. For this case `assert(callback != null)`, callback is a local variable and it is also not being called here.

When functions that has been executed are evaluated, we set the first token position of that function as a hit. That's probably the reason why a line like `assert( () { ` will be marked as hit. Because the closure function starts in this line.
