### ISSUE TITLE
Ignore files from coverage by path pattern

### ISSUE THREAD

**Issue by shouichi** [dart-lang/coverage#313]
Currently, `// coverage:ignore-file` is available for ignoring the whole file from coverage but some tools (such as built_value_generator) do not generate files with that meta-comment. It would be nice if we can ignore generated files from coverage by specifying something like `--exclude *.g.dart`. We could fix tools to add the meta-comment but it may make more sense to let developers choose whether to exclude generated files from coverage or not. Thank you.

**Comment by cbracken** [comment]
There are currently a variety of flags relating to scoping coverage collection/reporting.

collect_coverage has:
* `--scope-output`: limit coverage to just the specified package path
* `--include-dart`: compute coverage for dart: libraries

format_coverage has:
* `report-on`: specify files/directories to report coverage on

I wonder if it might make sense to add a matching `--no-report-on` option to `format_coverage` where people can list a set of glob patterns to exclude? Would that work for you?

Side note to myself/other maintainers: long term, I think it'd be nice for us to move these options into `collect_coverage` and reduce the amount of input earlier in the process. The tricky part there is file path to package URI mapping, but this is probably significantly easier than it was before Dart 2.0.

**Comment by shouichi** [comment]
> Would that work for you?

We use flutter and it emits `lcov.info` file when running `flutter test --coverage`. I honestly don't know the internal but it seems like flutter doesn't use `format_coverage`.

https://github.com/flutter/flutter/blob/e8fbb43aacb70568e6c3d37bcad4f6f36e490523/packages/flutter_tools/lib/src/test/coverage_collector.dart#L116

It seems like flutter will support excluding certain files from coverage. It might be better to wait and see what happens. (Ignoring files from coverage is not critical for us.)

https://github.com/flutter/flutter/issues/25077#issuecomment-699538134

Thank you.

**Comment by cbracken** [comment]
It's been a long time since I originally added coverage support to Flutter, but I know most of the original code has been replaced with something a bit more custom and performant by @jonahwilliams. 

It might be worth filing a [new issue](https://github.com/flutter/flutter/issues/new/choose) against Flutter to request the ability to filter files for collection (`--coverage-include` and `--coverage-exclude` multi-flag that takes glob patterns) requesting this feature.

If that turns out to be out of scope for the Flutter tool, the LCOV file format is actually pretty straightforward, and there's a lot of (non-Flutter) tooling that supports manipulating LCOV, so it probably wouldn't be too difficult to filter the generated LCOV. You'd still incur the time cost of collecting the coverage, but that may not be too bad if it's just a small percentage of the total files you're collecting on.

**Comment by jonahwilliams** [comment]
Support for this could be added to the flutter tool here:

https://github.com/flutter/flutter/blob/fde120df6db033186baa3a624dc1a4d627530b9f/packages/flutter_tools/lib/src/commands/test.dart#L252

We have a chance to exclude any files that we want from coverage. I don't have any plans to add this in the short term but I would happily review pull requests that add this feature.

**Comment by zoechi** [comment]
https://pub.dev/packages/remove_from_coverage makes it easy to remove info for specific file patterns.
Also the `lcov` command allows to do that https://linux.die.net/man/1/lcov

**Comment by liamappelbe** [comment]
Fixed by #496
