### ISSUE TITLE
How to make abstract constructor get coverage properly?

### ISSUE THREAD

**Issue by moseskarunia** [dart-lang/coverage#338]
Dart version: 2.12.0
Test version: 1.16.5
Coverage version: 1.0.1

```
/// lib/converter.dart
abstract class ConvertToSnapshot<Snap> {
  const ConvertToSnapshot(); // Want to make this test-covered
  Snap call(Map<String, dynamic> data);
}

/// test/converter_test.dart
class SampleConvertToFailure implements ConvertToFailure {
  const SampleConvertToFailure() : super();
  @override
  Failure call(dynamic e) {
    throw UnimplementedError();
  }
}

test(
  'ConvertToSnapshot constructor should be called',
  () async {
    SampleConvertToSnapshot();
    /// Still doesn't count as covered
  },
);

test(
  'ConvertToSnapshot constructor should be called',
  () async {
    const SampleConvertToSnapshot();
    /// Still doesn't count as covered
  },
);
```

When I run above test, neither results in constructor get covered.

**Comment by liamappelbe** [comment]
@moseskarunia Try switching `class SampleConvertToFailure implements ConvertToFailure` from `implements` to `extends`.

When you use `implements`, you make a class that is compatible with the base class, but doesn't inherit any of its behavior. The coverage you're seeing is correct, because that constructor is never actually called. The `super()` call is calling the `Object` constructor.

I could add a rule to ignore coverage for constructors of abstract classes, but some people might put functional code in there, and that shouldn't be ignored. And the abstract thing is a bit of a red herring anyway, since I can repro like this:

```dart
abstract class AbstractFoo {
  AbstractFoo() { print("AbstractFoo"); }
}
class ConcreteFoo implements AbstractFoo {
  ConcreteFoo() : super() { print("ConcreteFoo"); }
}
```

`ConcreteFoo()` prints `"ConcreteFoo"`. But if I switch to this:

```dart
abstract class AbstractFoo {
  AbstractFoo() { print("AbstractFoo"); }
}
class ConcreteFoo extends AbstractFoo {
  ConcreteFoo() : super() { print("ConcreteFoo"); }
}
```

Now `ConcreteFoo()` prints `"AbstractFoo\nConcreteFoo"`. Both these examples do the same thing regardless of whether `AbstractFoo` has `abstract`.

If you don't want to (or can't) use `extends`, use the ignore tags like iapicca suggested.
