### ISSUE TITLE
CI failing

### ISSUE THREAD

**Issue by liamappelbe** [dart-lang/coverage#392]
https://github.com/dart-lang/coverage/actions/runs/2481699515

**Comment by liamappelbe** [comment]
git bisect says the culprit is https://dart-review.googlesource.com/c/sdk/+/247603

@alexmarkov As of the new async/await changes, lines 28, 29, 30 of [this test file](https://github.com/dart-lang/coverage/blob/master/test/test_files/test_app.dart#L28) are no longer considered coverable. What exactly was changed about async/await? Was await translated into a function call in the past, but is no longer a function call?

**Comment by alexmarkov** [comment]
My guess is that the following code in source_report.cc is no longer needed:

```dart
  // We skip compiled async functions.  Once an async function has
  // been compiled, there is another function with the same range which
  // actually contains the user code.
  if (!func.IsAsyncFunction() && !func.IsAsyncGenerator() &&
      !func.IsSyncGenerator()) {
```
(https://github.com/dart-lang/sdk/blob/70412665f1d8f070a332d56f323d7c4e99d9db4f/runtime/vm/source_report.cc#L556-L559)

In the old implementation of async function the whole body of async/async*/sync* function was moved into a synthetic closure, and original function was also replaced with a synthetic body. So coverage previously saw 2 compiled functions and ignored the async/async*/sync* function with a synthetic body (only handling a closure with a real body). With new implementation of async/async* there is only 1 function, similar to regular functions.

We can try fixing this bug by removing that condition (or changing it to `if (!func.IsSyncGenerator())` as sync* functions still use old implementation).

We should also make sure to have enough tests for coverage in Dart SDK in order to catch such bugs earlier. (I would have found that condition earlier if there was at least one failing test for coverage of an async function in Dart SDK.)

**Comment by liamappelbe** [comment]
Waiting for the fix to roll into dev. I think I'll also need to update one of the branch coverage tests after the roll, because this change also means that some branch coverage info is no longer skipped.
