### ISSUE TITLE
File gets removed from coverage wrongly when "// coverage:ignore-file" is used in Strings

### ISSUE THREAD

**Issue by jtdLab** [dart-lang/coverage#413]
## Steps to Reproduce

1. Create new dart project using `dart create  example`
2. Update `lib/example.dart` so it looks like this:

```dart
int calculate() {
  print('// coverage:ignore-file'); // <- this line leads to the file being excluded from coverage
  return 6 * 7;
}
```
3. Execute `dart test --coverage` from the root of the project

**Expected results:** 
The generated `coverage/lcov.info` should contain coverage information about the file `lib/example.dart`

**Actual results:** 
The generated `coverage/lcov.info` does NOT contain  coverage information about the file `lib/example.dart`

**Comment by liamappelbe** [comment]
At the moment we just split the file into lines and check if the line contains any of the ignore comments.

A full fix for this bug would involve parsing all the string literals, and only searching for the comments outside of the strings.

A quicker fix would be to switch from checking that the line *contains* the ignore comment to checking that it *ends* with it. We can't just check that the whole line matches (with optional white-space at the start), because it's common practice to put these lines at the end of a normal line of code.

This doesn't solve the problem for multi-line strings, where the comment could still appear on its own line, but hopefully that's an edge case on an edge case.

I'm also going to allow white-space *after* the comment, because otherwise there will be very tricky to debug errors:

```dart
// One of these is invalid:
// coverage:ignore-file
// coverage:ignore-file     
```
